---
services:
  postgis:
    image: 'postgis/postgis'
    #volumes:
    #  - '/opt/data/:/opt/data'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    restart: unless-stopped
    ports:
      - '5432:5432'

  router:
    image: 'ghcr.io/gis-ops/docker-valhalla/valhalla:latest'
    environment:
      - server_threads=12
    ports:
      - '8002:8002'
    volumes:
      - $PWD/data/routing:/custom_files